[WIP] function for rerooting neuron
natverse/nat pull request #463
Opened 2021-05-28 09:44 UTC by dokato

getting foot in the door.

TODO:

- [ ] "And it should give the option to provide either indices or ids. See `nat::distal_to` for ideas."

2021-05-28 12:20 UTC, dokato commented
> and pointno for both

Here I decided to be more flexible and rather than point belonging to neuron I provide an option to reroot to a node that is closest to `point`

2021-06-01 14:30 UTC, dokato commented
@jefferis I'd appreciate advice on how to go around this point:

>  finally we will need a specialised catmaidneuron method that ensures that additional metadata

It was tempting to just use a function from catmaid:

```r
#' @export
reroot.catmaidneuron<-function(object, ...) {
  n = NextMethod()
  copy_tags_connectors(n, object)
}
```

But this should go to catmaid then? Here it'd introduce a dependency loop.

2021-06-01 14:33 UTC, jefferis commented
Thanks @dokato! `reroot.catmaidneuron` should be in `catmaid`. In future we should move some of the support for neurons with connectivity from `catmaid` into `nat`. But that will be a medium-sized change, so we should probably plan that separately.

2021-06-03 09:08 UTC, jefferis requested changes
I would not run pkgdown as part of the PR. Could you remove those changes under `docs`. I've now started running pkgdown on github for new packages, but for now, prefer to run it periodically on master after changes have gone in.

2021-06-03 09:08 UTC, jefferis commented on R/neuron.R
>    if (is.null(idx) && is.null(point)) return(x)
I suppose this is ok, although normally I would error on the basis that this was a bad call.

2021-06-03 09:08 UTC, jefferis commented on R/neuron.R
> +    nx <- as.neuron(as.ngraph(x), origin = x$d$PointNo[idx])
Yes this is correct, origin uses ids if they exist. I would still prefer to have the option to specify indices or ids in the arguments to this new `reroot` function though.

2021-06-03 09:08 UTC, jefferis commented on R/neuron.R
> +    nx <- as.neuron(as.ngraph(x), origin = nid)
I would normally avoid the repetition of this line by setting nid based on what kind of input we have and then doing as.neuron only once.

2021-06-03 09:08 UTC, jefferis commented on R/neuron.R
> +  if (is.null(idx) && is.null(point)) return(x)
again not certain if this is the right thing to do.

2021-06-03 09:08 UTC, jefferis commented on R/neuron.R
> +      res <- nmapply(reroot, x, point=as.data.frame(t(point)))
this looks fine, but typically I do points as matrices.

2021-06-03 09:08 UTC, jefferis commented on R/neuron.R
> +#' @param point numeric with X,Y,Z coordinates (data.frame for neuronlist)
(data.frame or Nx3 matrix for neuronlist)

2021-06-03 09:08 UTC, jefferis commented on R/neuron.R
> +reroot.neuronlist<-function(x, idx=NULL, point=NULL){
would like to have the option of id or idx here.

2021-06-03 09:08 UTC, jefferis commented on README.md
> +[<img src="https://media.springernature.com/w200/springer-static/cover-hires/journal/41586/478/7368" alt="Cell 2013 Abstract" style="height: 200px;"/>)](http://dx.doi.org/10.1038/nature10428)
Was this on purpose? Something odd here.

2021-06-03 09:57 UTC, dokato commented on README.md
> +[<img src="https://media.springernature.com/w200/springer-static/cover-hires/journal/41586/478/7368" alt="Cell 2013 Abstract" style="height: 200px;"/>)](http://dx.doi.org/10.1038/nature10428)
sorry, this should be part of a different PR, I just noticed that this nature cover doesn't show up, since I thought I should rebuild the docs as part of this PR I wanted to fix it 
![Screenshot 2021-06-03 at 10 56 09](https://user-images.githubusercontent.com/4547289/120626315-72f9b400-c45a-11eb-8850-d9e83162476d.png)

2021-06-03 10:29 UTC, dokato commented on R/neuron.R
> +      res <- nmapply(reroot, x, point=as.data.frame(t(point)))
added support for matrices

2021-06-03 11:07 UTC, dokato commented
Thanks @jefferis for useful comments, I added support for matrices, node ids and removed pkgdown build. PTAL now.

2021-06-03 11:14 UTC, dokato commented
BTW while on that I gave it a go and added `reroot.catmaidneuron` to https://github.com/natverse/rcatmaid

But for some reason I'm getting such error:
```r
> conn=catmaid_login(server="https://l1em.catmaid.virtualflybrain.org")
> orns=read.neurons.catmaid("name:ORN right", .progress='text')
> class(orns[[1]])
[1] "catmaidneuron" "neuron"
> reroot.catmaidneuron(orns[[1]])
Error in NextMethod() : generic function not specified
```
I'm using `nat` version with the reroot changes ofkz. Maybe I miss something about generics, but I believe that I found some relevant example where the "next" method came from a different package - similar to our case. Any ideas what's wrong here?

2021-06-03 11:34 UTC, jefferis commented
Maybe you need to import the generic from nat?

Sent from my iPhone

> On 3 Jun 2021, at 12:15, dokato ***@***.***> wrote:
> 
> ﻿
> BTW while on that I gave it a go and added reroot.catmaidneuron to https://github.com/natverse/rcatmaid
> 
> But for some reason I'm getting such error:
> 
> > conn=catmaid_login(server="https://l1em.catmaid.virtualflybrain.org")
> > orns=read.neurons.catmaid("name:ORN right", .progress='text')
> > class(orns[[1]])
> [1] "catmaidneuron" "neuron"
> > reroot.catmaidneuron(orns[[1]])
> Error in NextMethod() : generic function not specified
> I'm using nat version with the reroot changes ofkz. Maybe I miss something about generics, but I believe that I found some relevant example where the "next" method came from a different package - similar to our case. Any ideas what's wrong here?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-03 11:35 UTC, jefferis commented
Oh also you shouldn’t call the method directly. Use the generic ie plain reroot. 

Sent from my iPhone

> On 3 Jun 2021, at 12:15, dokato ***@***.***> wrote:
> 
> ﻿
> BTW while on that I gave it a go and added reroot.catmaidneuron to https://github.com/natverse/rcatmaid
> 
> But for some reason I'm getting such error:
> 
> > conn=catmaid_login(server="https://l1em.catmaid.virtualflybrain.org")
> > orns=read.neurons.catmaid("name:ORN right", .progress='text')
> > class(orns[[1]])
> [1] "catmaidneuron" "neuron"
> > reroot.catmaidneuron(orns[[1]])
> Error in NextMethod() : generic function not specified
> I'm using nat version with the reroot changes ofkz. Maybe I miss something about generics, but I believe that I found some relevant example where the "next" method came from a different package - similar to our case. Any ideas what's wrong here?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-03 12:08 UTC, dokato commented
ah damn, of course, that was it :P I'll send PR soon.

2021-06-03 12:27 UTC, jefferis commented
Actually @dokato the generic should have signature (x, ...) and the method should have ... in addition to the named arguments. Generics should pretty much always have ... so that you can handle any subsequent methods that need other arguments.

2021-06-03 12:56 UTC, jefferis commented on NEWS.md
> +* `reroot` function added with support for neuronlist (@dokato).
```
(#463, @dokato)
```

2021-06-03 13:03 UTC, jefferis commented on R/neuron.R
> +      target_pt=xyz[leaves_target,]
@dokato are these changes just whitespace. Although one can suppress whitespace in the github diff, I try to keep unrelated changes out of a PR if possible. Don't worry about it this time though.

2021-06-03 13:07 UTC, dokato commented on R/interactive.R
> +        corrected = reroot(w, selected.pointno)
sure, done!

2021-06-03 13:14 UTC, jefferis commented on R/neuron.R
> +    stop("One argument (idx, point, pointno) must be specified.")
Sorry one more thing. Don't you want exactly one of these? You could do:
```
sum(c(is.null(idx), is.null(point), is.null(pointno)))!=1
```

2021-06-03 13:34 UTC, dokato commented on R/neuron.R
> +    stop("One argument (idx, point, pointno) must be specified.")
yeap, that look better (although should be `!is.null[...]`). I replaced that in `reroot.neuron` too and added tests for that.

2021-06-03 13:45 UTC, jefferis commented on R/neuron.R
> +    stop("One argument (idx, point, pointno) must be specified.")
sorry yes
```
sum(c(is.null(idx), is.null(point), is.null(pointno)))!=2
```

2021-06-03 16:43 UTC, jefferis commented
@dokato I added some details to the docs. I'll merge when the checks complete.

2021-06-05 07:49 UTC, merged